default:
    site:
        # Standard Site Configuration
        url: http://doc.nuxeo.com
        name: Nuxeo Documentation
        twitter: nuxeo
        segment_write_key: "4qquvje3fv"

        # For RSS feeds
        title: 'Nuxeo Documentation'
        author: 'Nuxeo'
        review_messages:
            overdue: This page needs to be reviewed
            invalid_date: Invalid Review Date
            not_set: Review Date Not Set
    page_defaults:
        -
            pattern: "**/*.{md,html}"
            defaults:
                meta:
                    page-tag:
                        - CMIS
        -
            pattern: "**/*.md"
            defaults:
                layout: 'default.hbs'
    markdown_options:
        langPrefix : ''
        gfm        : true
        breaks     : false
        tables     : true
        pedantic   : false
        smartypants: false
        sanitize   : false
    repositories:
        static:
            url: git@github.com:nuxeo/doc.nuxeo.com-static-spaces.git
            branches:
                - master
        platform:
            url: git@github.com:nuxeo/doc.nuxeo.com-platform-spaces.git
            branches:
                - master
                - '710'
                - '60'
                - '58'

development:
    isDev: true
    site:
        segment_write_key: ""
